server:
  port: 8767
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Julyboby/SpringcloudConfig.git
          search-paths: respo
          #如果是私有仓库需要填写用户名密码，公开仓库则不配置。
          #username:
          #password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/