#jdbc datasource
#数据源的基本配置
spring:
  datasource:
    url: jdbc:mysql://192.168.83.73:3306/datajpa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 50000
      test-on-borrow: true

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    database: mysql
    #该配置自动检查实体和数据库表是否一致，如果不一致则会进行更新数据库表，
    hibernate:
      ddl-auto: update
    #显示sql语句
    show-sql: true

#服务器访问端口设置
server:
  port: 8080
