#server:
#  port: 8768
#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      label: master #指明远程仓库的分支
#      profile: dev #dev开发环境配置文件;test测试环境;pro正式环境
#      uri: http://localhost:8767/ #指明配置服务中心的网址

